### ISSUE TITLE
Integrate use of query web server. 

### ISSUE THREAD

**Issue by harishtella** [probcomp/inferenceql.viz#25]
## Enhancement
Make use of the new query web server for processing queries instead of locally calling `inferenceql.query/q`.

This is the PR that introduces the new query web server to iql.query.
https://github.com/probcomp/inferenceql.query/pull/38

## Todos

- [x] Use a reframe http effect to make calls to query webserver. 
- [x] Handle all cases of errors related web server responses.
- [x] Work with @zane to solve the issues outlined in the query webserver PR comments. 
- [x] Make app switch between local iql.query engine and webserver query engine based on `config.edn` settings.

#### Better documentation

- [x] Develop new re-frame event documentation scheme
- [x] Use new documentation scheme in events that this work touches. 

## Time 

_last updated: 07/10/20_
Time spent: ~ 4 day spent
Time left: 1 day
