### ISSUE TITLE
MILESTONE: Allow model and dataset upload

### ISSUE THREAD

**Issue by harishtella** [probcomp/inferenceql.viz#31]
This new feature should allow users to upload models and datasets via the browser FILE API (selecting files using the file browser or drag and drop). 

Or the user can specify a magic-url which will pull all relevant files and configuration information from that url. 

#### TODOS

- [x] Look into how the HTML 5 file api works 
https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications
- [x] Make UI changes for selecting files 
- [x] Allow the user to upload a model file and dataset file
- [x] Allow the user to upload a model file and dataset file by specifying a web url. 
- [x] Add basic error handling
- [ ] Add better error handling
- [x] Allow the user to upload models in the `bayes-db-export` format.
- [x] Convert models uploaded in the `bayes-db-export` format to Nick’s XCat models so they can be used by the IQL app 
- [ ] Allow the user to upload geodata and geodata settings via the file upload panel so that new maps can be brought into the app .(we may delay on this)

#### TODOS (related to hosting data)

- [x] Set up basic hosting of datasets/models in a repo 
- [x] Find a way to password protect magic-url's 
- [x] Automate pushing of datasets/models-repo to the web.

#### TODOS (these are more of a target after Zane has merged in his changes related to query editing.)
- [ ] Allow the user to upload multiple pairs of model files and dataset files.

#### TIME
Update 08/28/20: 
Time spent: ~ 1 day

Update 09/04/20: 
Time spent: ~ 1 week

Update 09/11/20
Time spent: ~ 2 weeks

Update 09/18/20
Time spent: ~ 3 weeks

![image](https://user-images.githubusercontent.com/362292/92270069-61778180-eeb3-11ea-996b-4f1f94bcd69d.png)
