### ISSUE TITLE
Handsontable is highlighting incorrect rows after sorting. 

### ISSUE THREAD

**Issue by harishtella** [probcomp/inferenceql.viz#87]
## Tasks

- [x] Post about this issue on the Handsontable project issue board
https://github.com/handsontable/handsontable/issues/7158

- [x] Find solution. It seems fairly straightforward. 

- [x] Make appropriate fixes in search-by-label branch
